/**
 * Mock data for Visitor Management
 */

import { Visitor } from './types';

export const mockVisitors: Visitor[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1-555-0123',
    company: 'Tech Solutions Inc.',
    photoUrl: null,
    purpose: 'meeting',
    hostEmployeeId: 'emp001',
    hostEmployeeName: 'Sarah Johnson',
    hostEmployeeEmail: 'sarah.johnson@company.com',
    hostDepartment: 'Sales',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '02:00 PM',
    expectedDepartureTime: '04:00 PM',
    registrationType: 'pre-registered',
    notes: 'VIP client from New York office',
    status: 'approved',
    checkInTime: null,
    checkOutTime: null,
    createdBy: 'emp001',
    createdByName: 'Sarah Johnson',
    createdAt: '2025-12-20T10:30:00Z',
    updatedAt: '2025-12-20T11:00:00Z',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    email: 'maria.garcia@techvendor.com',
    phone: '+1-555-0234',
    company: 'TechVendor Services',
    photoUrl: null,
    purpose: 'vendor',
    hostEmployeeId: 'emp002',
    hostEmployeeName: 'Mike Chen',
    hostEmployeeEmail: 'mike.chen@company.com',
    hostDepartment: 'IT',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '09:00 AM',
    expectedDepartureTime: '12:00 PM',
    registrationType: 'pre-registered',
    notes: 'Regular maintenance vendor',
    status: 'checked-in',
    checkInTime: '2025-12-23T08:55:00Z',
    checkOutTime: null,
    createdBy: 'emp002',
    createdByName: 'Mike Chen',
    createdAt: '2025-12-22T09:00:00Z',
    updatedAt: '2025-12-23T08:55:00Z',
  },
  {
    id: '3',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@email.com',
    phone: '+91-98765-43210',
    company: null,
    photoUrl: null,
    purpose: 'interview',
    hostEmployeeId: 'emp003',
    hostEmployeeName: 'Lisa Anderson',
    hostEmployeeEmail: 'lisa.anderson@company.com',
    hostDepartment: 'HR',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '10:30 AM',
    expectedDepartureTime: '12:30 PM',
    registrationType: 'pre-registered',
    notes: 'Senior Developer position - Technical round',
    status: 'approved',
    checkInTime: null,
    checkOutTime: null,
    createdBy: 'emp003',
    createdByName: 'Lisa Anderson',
    createdAt: '2025-12-18T14:00:00Z',
    updatedAt: '2025-12-18T14:00:00Z',
  },
  {
    id: '4',
    name: 'Alex Thompson',
    email: 'alex.t@deliveries.com',
    phone: '+1-555-0345',
    company: 'QuickDeliver Co.',
    photoUrl: null,
    purpose: 'delivery',
    hostEmployeeId: 'emp001',
    hostEmployeeName: 'Sarah Johnson',
    hostEmployeeEmail: 'sarah.johnson@company.com',
    hostDepartment: 'Reception',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '11:20 AM',
    expectedDepartureTime: null,
    registrationType: 'instant',
    notes: 'Urgent delivery - signature required',
    status: 'pending',
    checkInTime: null,
    checkOutTime: null,
    createdBy: 'reception',
    createdByName: 'Reception Desk',
    createdAt: '2025-12-23T11:20:00Z',
    updatedAt: '2025-12-23T11:20:00Z',
  },
  {
    id: '5',
    name: 'David Kim',
    email: 'david.kim@personal.com',
    phone: '+1-555-0456',
    company: null,
    photoUrl: null,
    purpose: 'personal',
    hostEmployeeId: 'emp004',
    hostEmployeeName: 'Tom Wilson',
    hostEmployeeEmail: 'tom.wilson@company.com',
    hostDepartment: 'Marketing',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '12:30 PM',
    expectedDepartureTime: null,
    registrationType: 'instant',
    notes: 'Meeting for lunch',
    status: 'rejected',
    checkInTime: null,
    checkOutTime: null,
    createdBy: 'reception',
    createdByName: 'Reception Desk',
    createdAt: '2025-12-23T12:30:00Z',
    updatedAt: '2025-12-23T12:35:00Z',
  },
  {
    id: '6',
    name: 'Anna Kowalski',
    email: 'anna.k@consultancy.com',
    phone: '+44-7700-900123',
    company: 'Business Consultancy Ltd',
    photoUrl: null,
    purpose: 'meeting',
    hostEmployeeId: 'emp005',
    hostEmployeeName: 'Robert Brown',
    hostEmployeeEmail: 'robert.brown@company.com',
    hostDepartment: 'Executive',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '03:00 PM',
    expectedDepartureTime: '05:30 PM',
    registrationType: 'pre-registered',
    notes: 'Executive meeting room reserved',
    status: 'checked-out',
    checkInTime: '2025-12-23T14:55:00Z',
    checkOutTime: '2025-12-23T17:25:00Z',
    createdBy: 'emp005',
    createdByName: 'Robert Brown',
    createdAt: '2025-12-15T16:00:00Z',
    updatedAt: '2025-12-23T17:25:00Z',
  },
];

// Mock employees for host selection
export const mockEmployees = [
  { id: 'emp001', name: 'Sarah Johnson', email: 'sarah.johnson@company.com', department: 'Sales' },
  { id: 'emp002', name: 'Mike Chen', email: 'mike.chen@company.com', department: 'IT' },
  { id: 'emp003', name: 'Lisa Anderson', email: 'lisa.anderson@company.com', department: 'HR' },
  { id: 'emp004', name: 'Tom Wilson', email: 'tom.wilson@company.com', department: 'Marketing' },
  { id: 'emp005', name: 'Robert Brown', email: 'robert.brown@company.com', department: 'Executive' },
  { id: 'emp006', name: 'Jennifer Davis', email: 'jennifer.davis@company.com', department: 'Finance' },
  { id: 'emp007', name: 'Carlos Rodriguez', email: 'carlos.rodriguez@company.com', department: 'Operations' },
  { id: 'emp008', name: 'Priya Patel', email: 'priya.patel@company.com', department: 'Engineering' },
];
