/**
 * Mock data for Visitor Management
 */

import { Visitor } from './types';

export const mockVisitors: Visitor[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1-555-0123',
    company: 'Tech Solutions Inc.',
    idType: 'passport',
    idNumber: 'P12345678',
    purpose: 'meeting',
    purposeDetails: 'Quarterly business review meeting',
    hostEmployeeId: 'emp001',
    hostEmployeeName: 'Sarah Johnson',
    hostEmployeeEmail: 'sarah.johnson@company.com',
    hostDepartment: 'Sales',
    registrationType: 'pre-registered',
    registeredBy: 'emp001',
    registeredByName: 'Sarah Johnson',
    registrationDate: '2025-12-20T10:30:00Z',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '02:00 PM',
    expectedDepartureTime: '04:00 PM',
    status: 'approved',
    approvalStatus: 'approved',
    approvedBy: 'emp001',
    approvedByName: 'Sarah Johnson',
    approvalDate: '2025-12-20T11:00:00Z',
    badgeNumber: 'V001',
    escortRequired: false,
    notes: 'VIP client from New York office',
    vehicleNumber: 'NY-1234',
    createdAt: '2025-12-20T10:30:00Z',
    updatedAt: '2025-12-20T11:00:00Z',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    email: 'maria.garcia@techvendor.com',
    phone: '+1-555-0234',
    company: 'TechVendor Services',
    idType: 'driving_license',
    idNumber: 'DL987654',
    purpose: 'vendor',
    purposeDetails: 'Equipment maintenance and inspection',
    hostEmployeeId: 'emp002',
    hostEmployeeName: 'Mike Chen',
    hostEmployeeEmail: 'mike.chen@company.com',
    hostDepartment: 'IT',
    registrationType: 'pre-registered',
    registeredBy: 'emp002',
    registeredByName: 'Mike Chen',
    registrationDate: '2025-12-22T09:00:00Z',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '09:00 AM',
    expectedDepartureTime: '12:00 PM',
    status: 'checked-in',
    approvalStatus: 'approved',
    approvedBy: 'emp002',
    approvedByName: 'Mike Chen',
    approvalDate: '2025-12-22T09:15:00Z',
    actualCheckInTime: '2025-12-23T08:55:00Z',
    checkedInBy: 'reception',
    checkedInByName: 'Reception Desk',
    badgeNumber: 'V002',
    escortRequired: true,
    notes: 'Regular maintenance vendor',
    createdAt: '2025-12-22T09:00:00Z',
    updatedAt: '2025-12-23T08:55:00Z',
  },
  {
    id: '3',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@email.com',
    phone: '+91-98765-43210',
    company: 'Self',
    idType: 'national_id',
    idNumber: 'AADHAR123456',
    purpose: 'interview',
    purposeDetails: 'Senior Developer position - Technical round',
    hostEmployeeId: 'emp003',
    hostEmployeeName: 'Lisa Anderson',
    hostEmployeeEmail: 'lisa.anderson@company.com',
    hostDepartment: 'HR',
    registrationType: 'pre-registered',
    registeredBy: 'emp003',
    registeredByName: 'Lisa Anderson',
    registrationDate: '2025-12-18T14:00:00Z',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '10:30 AM',
    expectedDepartureTime: '12:30 PM',
    status: 'approved',
    approvalStatus: 'approved',
    approvedBy: 'emp003',
    approvedByName: 'Lisa Anderson',
    approvalDate: '2025-12-18T14:15:00Z',
    badgeNumber: 'V003',
    escortRequired: false,
    notes: 'Conference room 3 booked',
    createdAt: '2025-12-18T14:00:00Z',
    updatedAt: '2025-12-18T14:15:00Z',
  },
  {
    id: '4',
    name: 'Emily Watson',
    email: 'emily.watson@courier.com',
    phone: '+1-555-0345',
    company: 'Express Couriers',
    purpose: 'delivery',
    purposeDetails: 'Package delivery for IT department',
    hostEmployeeId: 'reception',
    hostEmployeeName: 'Reception Desk',
    hostEmployeeEmail: 'reception@company.com',
    hostDepartment: 'Reception',
    registrationType: 'instant',
    registeredBy: 'reception',
    registeredByName: 'Reception Desk',
    registrationDate: '2025-12-23T11:20:00Z',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '11:20 AM',
    status: 'pending',
    approvalStatus: 'pending',
    escortRequired: false,
    notes: 'Urgent delivery - signature required',
    createdAt: '2025-12-23T11:20:00Z',
    updatedAt: '2025-12-23T11:20:00Z',
  },
  {
    id: '5',
    name: 'David Kim',
    email: 'david.kim@personal.com',
    phone: '+1-555-0456',
    purpose: 'personal',
    purposeDetails: 'Meeting for lunch',
    hostEmployeeId: 'emp004',
    hostEmployeeName: 'Tom Wilson',
    hostEmployeeEmail: 'tom.wilson@company.com',
    hostDepartment: 'Marketing',
    registrationType: 'instant',
    registeredBy: 'reception',
    registeredByName: 'Reception Desk',
    registrationDate: '2025-12-23T12:30:00Z',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '12:30 PM',
    status: 'rejected',
    approvalStatus: 'rejected',
    approvedBy: 'emp004',
    approvedByName: 'Tom Wilson',
    approvalDate: '2025-12-23T12:35:00Z',
    rejectionReason: 'Not available - in external meeting',
    escortRequired: false,
    createdAt: '2025-12-23T12:30:00Z',
    updatedAt: '2025-12-23T12:35:00Z',
  },
  {
    id: '6',
    name: 'Anna Kowalski',
    email: 'anna.k@consultancy.com',
    phone: '+44-7700-900123',
    company: 'Business Consultancy Ltd',
    idType: 'passport',
    idNumber: 'GB9876543',
    purpose: 'meeting',
    purposeDetails: 'Strategy consultation session',
    hostEmployeeId: 'emp005',
    hostEmployeeName: 'Robert Brown',
    hostEmployeeEmail: 'robert.brown@company.com',
    hostDepartment: 'Executive',
    registrationType: 'pre-registered',
    registeredBy: 'emp005',
    registeredByName: 'Robert Brown',
    registrationDate: '2025-12-15T16:00:00Z',
    expectedArrivalDate: '2025-12-23',
    expectedArrivalTime: '03:00 PM',
    expectedDepartureTime: '05:30 PM',
    status: 'checked-out',
    approvalStatus: 'approved',
    approvedBy: 'emp005',
    approvedByName: 'Robert Brown',
    approvalDate: '2025-12-15T16:10:00Z',
    actualCheckInTime: '2025-12-23T14:55:00Z',
    actualCheckOutTime: '2025-12-23T17:25:00Z',
    checkedInBy: 'reception',
    checkedInByName: 'Reception Desk',
    checkedOutBy: 'reception',
    checkedOutByName: 'Reception Desk',
    badgeNumber: 'V004',
    escortRequired: false,
    notes: 'Executive meeting room reserved',
    vehicleNumber: 'LON-5678',
    createdAt: '2025-12-15T16:00:00Z',
    updatedAt: '2025-12-23T17:25:00Z',
  },
];

// Mock employees for host selection
export const mockEmployees = [
  { id: 'emp001', name: 'Sarah Johnson', email: 'sarah.johnson@company.com', department: 'Sales' },
  { id: 'emp002', name: 'Mike Chen', email: 'mike.chen@company.com', department: 'IT' },
  { id: 'emp003', name: 'Lisa Anderson', email: 'lisa.anderson@company.com', department: 'HR' },
  { id: 'emp004', name: 'Tom Wilson', email: 'tom.wilson@company.com', department: 'Marketing' },
  { id: 'emp005', name: 'Robert Brown', email: 'robert.brown@company.com', department: 'Executive' },
  { id: 'emp006', name: 'Jennifer Davis', email: 'jennifer.davis@company.com', department: 'Finance' },
  { id: 'emp007', name: 'Carlos Rodriguez', email: 'carlos.rodriguez@company.com', department: 'Operations' },
  { id: 'emp008', name: 'Priya Patel', email: 'priya.patel@company.com', department: 'Engineering' },
];
