/**
 * Mock Data for Room Management
 */

import { Company, Room, RoomBooking } from './types';

/**
 * Mock Companies (demonstrating subscription sharing)
 */
export const mockCompanies: Company[] = [
  {
    id: 'comp-001',
    name: 'TechCorp Solutions',
    subscriptionType: 'owner',
    isActive: true,
  },
  {
    id: 'comp-002',
    name: 'DesignHub Agency',
    subscriptionType: 'shared',
    ownerCompanyId: 'comp-001',
    isActive: true,
  },
  {
    id: 'comp-003',
    name: 'Marketing Pros Inc',
    subscriptionType: 'shared',
    ownerCompanyId: 'comp-001',
    isActive: true,
  },
  {
    id: 'comp-004',
    name: 'DataVault Systems',
    subscriptionType: 'owner',
    isActive: true,
  },
];

/**
 * Mock Rooms
 */
export const mockRooms: Room[] = [
  {
    id: 'room-001',
    name: 'Innovation Hub',
    description: 'Large conference room with state-of-the-art AV equipment, perfect for presentations and client meetings.',
    type: 'conference',
    status: 'available',
    capacity: 20,
    floor: '5th Floor',
    building: 'Building A',
    location: '5th Floor, Building A, West Wing',
    amenities: {
      projector: true,
      whiteboard: true,
      videoConference: true,
      audioSystem: true,
      wifi: true,
      television: true,
      airConditioning: true,
      smartBoard: true,
      refreshments: true,
    },
    ownerCompanyId: 'comp-001',
    sharedWithCompanies: ['comp-002', 'comp-003'],
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c',
    hourlyRate: 50,
    halfDayRate: 180,
    fullDayRate: 320,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-12-20T10:30:00Z',
    createdBy: 'user-001',
    createdByName: 'John Admin',
    availableFrom: '08:00',
    availableTo: '18:00',
    availableDays: [1, 2, 3, 4, 5],
    minBookingDuration: 30,
    maxBookingDuration: 480,
    bufferTime: 15,
    totalBookings: 145,
    utilizationRate: 68,
  },
  {
    id: 'room-002',
    name: 'Creative Studio',
    description: 'Modern meeting space designed for creative brainstorming and collaborative work.',
    type: 'meeting',
    status: 'available',
    capacity: 12,
    floor: '3rd Floor',
    building: 'Building A',
    location: '3rd Floor, Building A, East Wing',
    amenities: {
      projector: true,
      whiteboard: true,
      videoConference: true,
      wifi: true,
      airConditioning: true,
      smartBoard: true,
      refreshments: true,
    },
    ownerCompanyId: 'comp-001',
    sharedWithCompanies: ['comp-002'],
    imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2',
    hourlyRate: 35,
    halfDayRate: 120,
    fullDayRate: 200,
    createdAt: '2024-02-10T09:00:00Z',
    updatedAt: '2024-12-18T14:00:00Z',
    createdBy: 'user-001',
    createdByName: 'John Admin',
    availableFrom: '08:00',
    availableTo: '18:00',
    availableDays: [1, 2, 3, 4, 5],
    minBookingDuration: 30,
    maxBookingDuration: 360,
    bufferTime: 15,
    totalBookings: 98,
    utilizationRate: 55,
  },
  {
    id: 'room-003',
    name: 'Quick Connect',
    description: 'Compact huddle room for quick team sync-ups and small group discussions.',
    type: 'huddle',
    status: 'occupied',
    capacity: 6,
    floor: '2nd Floor',
    building: 'Building A',
    location: '2nd Floor, Building A, North Wing',
    amenities: {
      whiteboard: true,
      videoConference: true,
      wifi: true,
      airConditioning: true,
      television: true,
    },
    ownerCompanyId: 'comp-001',
    sharedWithCompanies: [],
    imageUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
    hourlyRate: 20,
    halfDayRate: 70,
    fullDayRate: 120,
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-12-23T09:00:00Z',
    createdBy: 'user-001',
    createdByName: 'John Admin',
    availableFrom: '08:00',
    availableTo: '18:00',
    availableDays: [1, 2, 3, 4, 5],
    minBookingDuration: 15,
    maxBookingDuration: 120,
    bufferTime: 10,
    totalBookings: 234,
    utilizationRate: 82,
  },
  {
    id: 'room-004',
    name: 'Executive Boardroom',
    description: 'Premium boardroom with elegant furnishings and advanced conference facilities for executive meetings.',
    type: 'boardroom',
    status: 'available',
    capacity: 16,
    floor: '10th Floor',
    building: 'Building A',
    location: '10th Floor, Building A, Executive Suite',
    amenities: {
      projector: true,
      whiteboard: true,
      videoConference: true,
      audioSystem: true,
      wifi: true,
      television: true,
      airConditioning: true,
      phoneConference: true,
      smartBoard: true,
      refreshments: true,
    },
    ownerCompanyId: 'comp-001',
    sharedWithCompanies: [],
    imageUrl: 'https://images.unsplash.com/photo-1497366672149-e5e4b4d34eb3',
    hourlyRate: 80,
    halfDayRate: 280,
    fullDayRate: 500,
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-12-22T16:00:00Z',
    createdBy: 'user-001',
    createdByName: 'John Admin',
    availableFrom: '08:00',
    availableTo: '20:00',
    availableDays: [1, 2, 3, 4, 5],
    minBookingDuration: 60,
    maxBookingDuration: 480,
    bufferTime: 30,
    totalBookings: 67,
    utilizationRate: 45,
  },
  {
    id: 'room-005',
    name: 'Learning Center',
    description: 'Spacious training room equipped with multiple screens and comfortable seating for workshops and training sessions.',
    type: 'training',
    status: 'maintenance',
    capacity: 30,
    floor: '4th Floor',
    building: 'Building B',
    location: '4th Floor, Building B, Training Wing',
    amenities: {
      projector: true,
      whiteboard: true,
      videoConference: true,
      audioSystem: true,
      wifi: true,
      television: true,
      airConditioning: true,
      smartBoard: true,
      refreshments: true,
    },
    ownerCompanyId: 'comp-001',
    sharedWithCompanies: ['comp-002', 'comp-003'],
    imageUrl: 'https://images.unsplash.com/photo-1497366858526-0766cadbe8fa',
    hourlyRate: 60,
    halfDayRate: 200,
    fullDayRate: 350,
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-12-23T08:00:00Z',
    createdBy: 'user-001',
    createdByName: 'John Admin',
    availableFrom: '08:00',
    availableTo: '18:00',
    availableDays: [1, 2, 3, 4, 5],
    minBookingDuration: 60,
    maxBookingDuration: 480,
    bufferTime: 30,
    totalBookings: 52,
    utilizationRate: 38,
  },
  {
    id: 'room-006',
    name: 'Collaboration Zone',
    description: 'Flexible meeting space with modular furniture for various team activities and workshops.',
    type: 'meeting',
    status: 'available',
    capacity: 15,
    floor: '3rd Floor',
    building: 'Building B',
    location: '3rd Floor, Building B, Collaboration Area',
    amenities: {
      whiteboard: true,
      videoConference: true,
      wifi: true,
      airConditioning: true,
      television: true,
      refreshments: true,
    },
    ownerCompanyId: 'comp-002',
    sharedWithCompanies: ['comp-001', 'comp-003'],
    imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2',
    hourlyRate: 30,
    halfDayRate: 100,
    fullDayRate: 180,
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-12-21T11:00:00Z',
    createdBy: 'user-005',
    createdByName: 'Sarah Designer',
    availableFrom: '08:00',
    availableTo: '18:00',
    availableDays: [1, 2, 3, 4, 5],
    minBookingDuration: 30,
    maxBookingDuration: 360,
    bufferTime: 15,
    totalBookings: 76,
    utilizationRate: 52,
  },
  {
    id: 'room-007',
    name: 'Grand Hall',
    description: 'Large event space suitable for company events, town halls, and large gatherings.',
    type: 'event',
    status: 'available',
    capacity: 100,
    floor: '1st Floor',
    building: 'Building A',
    location: '1st Floor, Building A, Main Event Area',
    amenities: {
      projector: true,
      videoConference: true,
      audioSystem: true,
      wifi: true,
      television: true,
      airConditioning: true,
      smartBoard: true,
      refreshments: true,
    },
    ownerCompanyId: 'comp-001',
    sharedWithCompanies: ['comp-002', 'comp-003'],
    imageUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678',
    hourlyRate: 150,
    halfDayRate: 500,
    fullDayRate: 900,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-12-20T15:00:00Z',
    createdBy: 'user-001',
    createdByName: 'John Admin',
    availableFrom: '08:00',
    availableTo: '22:00',
    availableDays: [0, 1, 2, 3, 4, 5, 6],
    minBookingDuration: 120,
    maxBookingDuration: 720,
    bufferTime: 60,
    totalBookings: 28,
    utilizationRate: 35,
  },
  {
    id: 'room-008',
    name: 'Focus Pod',
    description: 'Small private space for focused work or one-on-one meetings.',
    type: 'huddle',
    status: 'available',
    capacity: 4,
    floor: '2nd Floor',
    building: 'Building A',
    location: '2nd Floor, Building A, Quiet Zone',
    amenities: {
      whiteboard: true,
      wifi: true,
      airConditioning: true,
      television: true,
    },
    ownerCompanyId: 'comp-001',
    sharedWithCompanies: [],
    hourlyRate: 15,
    halfDayRate: 50,
    fullDayRate: 90,
    createdAt: '2024-04-01T09:00:00Z',
    updatedAt: '2024-12-22T10:00:00Z',
    createdBy: 'user-001',
    createdByName: 'John Admin',
    availableFrom: '08:00',
    availableTo: '18:00',
    availableDays: [1, 2, 3, 4, 5],
    minBookingDuration: 30,
    maxBookingDuration: 240,
    bufferTime: 10,
    totalBookings: 189,
    utilizationRate: 71,
  },
];

/**
 * Mock Bookings (showing cross-company bookings)
 */
export const mockBookings: RoomBooking[] = [
  {
    id: 'booking-001',
    roomId: 'room-001',
    roomName: 'Innovation Hub',
    title: 'Q4 Strategy Planning',
    description: 'Quarterly strategic planning session with all department heads',
    purpose: 'Board Meeting',
    startDateTime: '2024-12-23T10:00:00Z',
    endDateTime: '2024-12-23T12:00:00Z',
    date: '2024-12-23',
    recurrence: 'none',
    numberOfAttendees: 15,
    bookedBy: 'user-001',
    bookedByName: 'John Admin',
    bookedByEmail: 'john.admin@techcorp.com',
    bookedByCompanyId: 'comp-001',
    bookedByCompanyName: 'TechCorp Solutions',
    hasExternalGuests: false,
    status: 'confirmed',
    notifyAttendees: true,
    createdAt: '2024-12-15T09:00:00Z',
    updatedAt: '2024-12-15T09:00:00Z',
  },
  {
    id: 'booking-002',
    roomId: 'room-002',
    roomName: 'Creative Studio',
    title: 'Design Review - Project Phoenix',
    description: 'Review and feedback session for Phoenix project designs',
    purpose: 'Design Review',
    startDateTime: '2024-12-23T14:00:00Z',
    endDateTime: '2024-12-23T16:00:00Z',
    date: '2024-12-23',
    recurrence: 'none',
    numberOfAttendees: 8,
    bookedBy: 'user-005',
    bookedByName: 'Sarah Designer',
    bookedByEmail: 'sarah@designhub.com',
    bookedByCompanyId: 'comp-002',
    bookedByCompanyName: 'DesignHub Agency',
    hostName: 'Sarah Designer',
    hostEmail: 'sarah@designhub.com',
    hasExternalGuests: true,
    externalGuestCount: 2,
    externalGuestCompanies: ['Client XYZ Corp'],
    setupRequirements: 'Please arrange chairs in U-shape',
    status: 'confirmed',
    notifyAttendees: true,
    createdAt: '2024-12-18T11:00:00Z',
    updatedAt: '2024-12-18T11:00:00Z',
  },
  {
    id: 'booking-003',
    roomId: 'room-003',
    roomName: 'Quick Connect',
    title: 'Daily Standup - Dev Team',
    description: 'Daily synchronization meeting for development team',
    purpose: 'Team Meeting',
    startDateTime: '2024-12-23T09:00:00Z',
    endDateTime: '2024-12-23T09:30:00Z',
    date: '2024-12-23',
    recurrence: 'daily',
    recurrenceEndDate: '2024-12-31',
    numberOfAttendees: 6,
    bookedBy: 'user-002',
    bookedByName: 'Mike Developer',
    bookedByEmail: 'mike@techcorp.com',
    bookedByCompanyId: 'comp-001',
    bookedByCompanyName: 'TechCorp Solutions',
    hasExternalGuests: false,
    status: 'confirmed',
    notifyAttendees: false,
    createdAt: '2024-12-01T08:00:00Z',
    updatedAt: '2024-12-01T08:00:00Z',
    checkedInAt: '2024-12-23T08:58:00Z',
  },
  {
    id: 'booking-004',
    roomId: 'room-004',
    roomName: 'Executive Boardroom',
    title: 'Investor Presentation',
    description: 'Q4 results presentation to potential investors',
    purpose: 'Presentation',
    startDateTime: '2024-12-24T11:00:00Z',
    endDateTime: '2024-12-24T13:00:00Z',
    date: '2024-12-24',
    recurrence: 'none',
    numberOfAttendees: 12,
    bookedBy: 'user-003',
    bookedByName: 'Emily CFO',
    bookedByEmail: 'emily.cfo@techcorp.com',
    bookedByCompanyId: 'comp-001',
    bookedByCompanyName: 'TechCorp Solutions',
    hasExternalGuests: true,
    externalGuestCount: 5,
    externalGuestCompanies: ['Venture Capital Partners', 'Investment Group LLC'],
    cateringRequired: true,
    cateringDetails: 'Light refreshments and coffee service',
    setupRequirements: 'Boardroom style, presentation screen setup',
    status: 'confirmed',
    notifyAttendees: true,
    createdAt: '2024-12-10T14:00:00Z',
    updatedAt: '2024-12-10T14:00:00Z',
  },
  {
    id: 'booking-005',
    roomId: 'room-006',
    roomName: 'Collaboration Zone',
    title: 'Marketing Campaign Workshop',
    description: 'Brainstorming and planning for Q1 2025 marketing campaigns',
    purpose: 'Workshop',
    startDateTime: '2024-12-23T13:00:00Z',
    endDateTime: '2024-12-23T17:00:00Z',
    date: '2024-12-23',
    recurrence: 'none',
    numberOfAttendees: 10,
    bookedBy: 'user-007',
    bookedByName: 'Tom Marketing',
    bookedByEmail: 'tom@marketingpros.com',
    bookedByCompanyId: 'comp-003',
    bookedByCompanyName: 'Marketing Pros Inc',
    hasExternalGuests: false,
    cateringRequired: true,
    cateringDetails: 'Snacks and beverages for afternoon session',
    status: 'confirmed',
    notifyAttendees: true,
    createdAt: '2024-12-16T10:00:00Z',
    updatedAt: '2024-12-16T10:00:00Z',
  },
  {
    id: 'booking-006',
    roomId: 'room-001',
    roomName: 'Innovation Hub',
    title: 'Client Onboarding Meeting',
    description: 'Onboarding session for new enterprise client',
    purpose: 'Client Meeting',
    startDateTime: '2024-12-24T14:00:00Z',
    endDateTime: '2024-12-24T16:00:00Z',
    date: '2024-12-24',
    recurrence: 'none',
    numberOfAttendees: 12,
    bookedBy: 'user-004',
    bookedByName: 'Lisa Sales',
    bookedByEmail: 'lisa@techcorp.com',
    bookedByCompanyId: 'comp-001',
    bookedByCompanyName: 'TechCorp Solutions',
    hasExternalGuests: true,
    externalGuestCount: 6,
    externalGuestCompanies: ['Enterprise Client Inc'],
    cateringRequired: true,
    cateringDetails: 'Coffee, tea, and pastries',
    setupRequirements: 'Presentation setup with video conferencing',
    specialRequests: 'Please ensure room is set up 30 minutes early',
    status: 'pending',
    notifyAttendees: true,
    createdAt: '2024-12-20T15:00:00Z',
    updatedAt: '2024-12-20T15:00:00Z',
  },
  {
    id: 'booking-007',
    roomId: 'room-008',
    roomName: 'Focus Pod',
    title: 'Performance Review - John Doe',
    description: 'Annual performance review meeting',
    purpose: 'One-on-One',
    startDateTime: '2024-12-23T15:00:00Z',
    endDateTime: '2024-12-23T16:00:00Z',
    date: '2024-12-23',
    recurrence: 'none',
    numberOfAttendees: 2,
    bookedBy: 'user-006',
    bookedByName: 'HR Manager',
    bookedByEmail: 'hr@techcorp.com',
    bookedByCompanyId: 'comp-001',
    bookedByCompanyName: 'TechCorp Solutions',
    hasExternalGuests: false,
    status: 'confirmed',
    notifyAttendees: false,
    createdAt: '2024-12-22T09:00:00Z',
    updatedAt: '2024-12-22T09:00:00Z',
  },
];
