/**
 * Mock Policy Data
 */

import { Policy } from './types';

export const mockPolicies: Policy[] = [
  {
    id: 'POL001',
    name: 'Code of Conduct',
    description: 'Guidelines for professional behavior and ethical standards expected from all employees.',
    category: 'hr',
    status: 'active',
    version: '3.2',
    fileUrl: 'https://example.com/policies/code-of-conduct.pdf',
    fileType: 'pdf',
    fileSize: 2456789,
    effectiveDate: '2024-01-01',
    uploadedBy: 'USR001',
    uploadedByName: 'John Admin',
    uploadedAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-06-15T14:30:00Z',
    viewCount: 342,
    mandatory: true,
  },
  {
    id: 'POL002',
    name: 'Remote Work Policy',
    description: 'Guidelines and requirements for employees working remotely.',
    category: 'hr',
    status: 'active',
    version: '2.0',
    fileUrl: 'https://example.com/policies/remote-work.pdf',
    fileType: 'pdf',
    fileSize: 1845632,
    effectiveDate: '2024-03-01',
    uploadedBy: 'USR001',
    uploadedByName: 'John Admin',
    uploadedAt: '2024-02-28T09:15:00Z',
    viewCount: 256,
    mandatory: false,
  },
  {
    id: 'POL003',
    name: 'Data Security & Privacy Policy',
    description: 'Comprehensive guidelines for handling sensitive data and maintaining information security.',
    category: 'security',
    status: 'active',
    version: '4.1',
    fileUrl: 'https://example.com/policies/data-security.pdf',
    fileType: 'pdf',
    fileSize: 3256789,
    effectiveDate: '2024-01-15',
    expiryDate: '2025-01-14',
    uploadedBy: 'USR001',
    uploadedByName: 'John Admin',
    uploadedAt: '2024-01-10T11:20:00Z',
    updatedAt: '2024-09-01T16:45:00Z',
    viewCount: 478,
    mandatory: true,
  },
  {
    id: 'POL004',
    name: 'IT Acceptable Use Policy',
    description: 'Guidelines for appropriate use of company IT resources and equipment.',
    category: 'it',
    status: 'active',
    version: '2.5',
    fileUrl: 'https://example.com/policies/it-acceptable-use.pdf',
    fileType: 'pdf',
    fileSize: 1956432,
    effectiveDate: '2024-02-01',
    uploadedBy: 'USR002',
    uploadedByName: 'Sarah IT Manager',
    uploadedAt: '2024-01-28T13:30:00Z',
    viewCount: 312,
    mandatory: true,
  },
  {
    id: 'POL005',
    name: 'Leave and Attendance Policy',
    description: 'Detailed information about leave types, accrual, and attendance requirements.',
    category: 'hr',
    status: 'active',
    version: '3.0',
    fileUrl: 'https://example.com/policies/leave-attendance.pdf',
    fileType: 'pdf',
    fileSize: 2145678,
    effectiveDate: '2024-01-01',
    uploadedBy: 'USR003',
    uploadedByName: 'Mike HR Lead',
    uploadedAt: '2023-12-20T10:00:00Z',
    viewCount: 523,
    mandatory: false,
  },
  {
    id: 'POL006',
    name: 'Workplace Safety Guidelines',
    description: 'Safety protocols and emergency procedures for all office locations.',
    category: 'safety',
    status: 'active',
    version: '1.8',
    fileUrl: 'https://example.com/policies/workplace-safety.pdf',
    fileType: 'pdf',
    fileSize: 2856123,
    effectiveDate: '2024-04-01',
    uploadedBy: 'USR004',
    uploadedByName: 'Emily Safety Officer',
    uploadedAt: '2024-03-25T08:45:00Z',
    viewCount: 189,
    mandatory: true,
  },
  {
    id: 'POL007',
    name: 'Social Media Policy - Draft',
    description: 'Guidelines for employee use of social media in relation to company matters.',
    category: 'general',
    status: 'draft',
    version: '1.0',
    fileUrl: 'https://example.com/policies/social-media-draft.pdf',
    fileType: 'pdf',
    fileSize: 1456789,
    effectiveDate: '2025-01-01',
    uploadedBy: 'USR001',
    uploadedByName: 'John Admin',
    uploadedAt: '2024-11-15T14:20:00Z',
    viewCount: 45,
    mandatory: false,
  },
  {
    id: 'POL008',
    name: 'Anti-Harassment & Discrimination Policy',
    description: 'Zero-tolerance policy on harassment, discrimination, and creating a respectful workplace.',
    category: 'compliance',
    status: 'active',
    version: '2.3',
    fileUrl: 'https://example.com/policies/anti-harassment.pdf',
    fileType: 'pdf',
    fileSize: 2345678,
    effectiveDate: '2024-01-01',
    uploadedBy: 'USR001',
    uploadedByName: 'John Admin',
    uploadedAt: '2023-12-15T09:30:00Z',
    updatedAt: '2024-07-10T11:15:00Z',
    viewCount: 412,
    mandatory: true,
  },
];
