/**
 * Mock Policy Data
 */

import { Policy } from './types';

export const mockPolicies: Policy[] = [
  {
    id: 'POL001',
    name: 'Code of Conduct',
    description: 'Guidelines for professional behavior and ethical standards expected from all employees.',
    category: 'hr',
    status: 'published',
    currentVersion: '3.2',
    versions: [
      {
        versionNumber: '3.2',
        documentId: 'DOC001-v32',
        documentUrl: 'https://example.com/policies/code-of-conduct-v3.2.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 2456789,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2024-06-15T14:30:00Z',
        changeNotes: 'Updated social media guidelines and remote work ethics',
      },
      {
        versionNumber: '3.1',
        documentId: 'DOC001-v31',
        documentUrl: 'https://example.com/policies/code-of-conduct-v3.1.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 2356789,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2024-03-10T10:00:00Z',
        changeNotes: 'Minor corrections and clarifications',
      },
      {
        versionNumber: '3.0',
        documentId: 'DOC001-v30',
        documentUrl: 'https://example.com/policies/code-of-conduct-v3.0.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 2256789,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2024-01-01T10:00:00Z',
        changeNotes: 'Major update with new sections on DEI and workplace conduct',
      },
    ],
    effectiveDate: '2024-01-01',
    createdBy: 'USR001',
    createdByName: 'John Admin',
    createdAt: '2023-12-15T10:00:00Z',
    updatedAt: '2024-06-15T14:30:00Z',
    viewCount: 342,
    mandatory: true,
  },
  {
    id: 'POL002',
    name: 'Remote Work Policy',
    description: 'Guidelines and requirements for employees working remotely.',
    category: 'hr',
    status: 'published',
    currentVersion: '2.0',
    versions: [
      {
        versionNumber: '2.0',
        documentUrl: 'https://company-intranet.com/policies/remote-work',
        sourceType: 'url',
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2024-02-28T09:15:00Z',
        changeNotes: 'Added hybrid work schedule options',
      },
      {
        versionNumber: '1.0',
        documentId: 'DOC002-v10',
        documentUrl: 'https://example.com/policies/remote-work-v1.0.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 1745632,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2023-09-01T09:00:00Z',
        changeNotes: 'Initial version',
      },
    ],
    effectiveDate: '2024-03-01',
    createdBy: 'USR001',
    createdByName: 'John Admin',
    createdAt: '2023-09-01T09:00:00Z',
    updatedAt: '2024-02-28T09:15:00Z',
    viewCount: 256,
    mandatory: false,
  },
  {
    id: 'POL003',
    name: 'Data Security & Privacy Policy',
    description: 'Comprehensive guidelines for handling sensitive data and maintaining information security.',
    category: 'security',
    status: 'published',
    currentVersion: '4.1',
    versions: [
      {
        versionNumber: '4.1',
        documentId: 'DOC003-v41',
        documentUrl: 'https://example.com/policies/data-security-v4.1.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 3256789,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2024-09-01T16:45:00Z',
        changeNotes: 'Updated encryption standards and GDPR compliance requirements',
      },
      {
        versionNumber: '4.0',
        documentId: 'DOC003-v40',
        documentUrl: 'https://example.com/policies/data-security-v4.0.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 3156789,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2024-01-10T11:20:00Z',
        changeNotes: 'Major security framework update',
      },
    ],
    effectiveDate: '2024-01-15',
    expiryDate: '2025-01-14',
    createdBy: 'USR001',
    createdByName: 'John Admin',
    createdAt: '2024-01-10T11:20:00Z',
    updatedAt: '2024-09-01T16:45:00Z',
    viewCount: 478,
    mandatory: true,
  },
  {
    id: 'POL004',
    name: 'IT Acceptable Use Policy',
    description: 'Guidelines for appropriate use of company IT resources and equipment.',
    category: 'it',
    status: 'published',
    currentVersion: '2.5',
    versions: [
      {
        versionNumber: '2.5',
        documentId: 'DOC004-v25',
        documentUrl: 'https://example.com/policies/it-acceptable-use-v2.5.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 1956432,
        uploadedBy: 'USR002',
        uploadedByName: 'Sarah IT Manager',
        uploadedAt: '2024-01-28T13:30:00Z',
        changeNotes: 'Added AI tool usage guidelines',
      },
    ],
    effectiveDate: '2024-02-01',
    createdBy: 'USR002',
    createdByName: 'Sarah IT Manager',
    createdAt: '2024-01-28T13:30:00Z',
    viewCount: 312,
    mandatory: true,
  },
  {
    id: 'POL005',
    name: 'Leave and Attendance Policy',
    description: 'Detailed information about leave types, accrual, and attendance requirements.',
    category: 'hr',
    status: 'published',
    currentVersion: '3.0',
    versions: [
      {
        versionNumber: '3.0',
        documentId: 'DOC005-v30',
        documentUrl: 'https://example.com/policies/leave-attendance-v3.0.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 2145678,
        uploadedBy: 'USR003',
        uploadedByName: 'Mike HR Lead',
        uploadedAt: '2023-12-20T10:00:00Z',
        changeNotes: 'Added parental leave and bereavement leave details',
      },
    ],
    effectiveDate: '2024-01-01',
    createdBy: 'USR003',
    createdByName: 'Mike HR Lead',
    createdAt: '2023-12-20T10:00:00Z',
    viewCount: 523,
    mandatory: false,
  },
  {
    id: 'POL006',
    name: 'Workplace Safety Guidelines',
    description: 'Safety protocols and emergency procedures for all office locations.',
    category: 'safety',
    status: 'published',
    currentVersion: '1.8',
    versions: [
      {
        versionNumber: '1.8',
        documentId: 'DOC006-v18',
        documentUrl: 'https://example.com/policies/workplace-safety-v1.8.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 2856123,
        uploadedBy: 'USR004',
        uploadedByName: 'Emily Safety Officer',
        uploadedAt: '2024-03-25T08:45:00Z',
        changeNotes: 'Updated fire evacuation procedures',
      },
    ],
    effectiveDate: '2024-04-01',
    createdBy: 'USR004',
    createdByName: 'Emily Safety Officer',
    createdAt: '2024-03-25T08:45:00Z',
    viewCount: 189,
    mandatory: true,
  },
  {
    id: 'POL007',
    name: 'Social Media Policy - Draft',
    description: 'Guidelines for employee use of social media in relation to company matters.',
    category: 'general',
    status: 'draft',
    currentVersion: '1.0',
    versions: [
      {
        versionNumber: '1.0',
        documentId: 'DOC007-v10',
        documentUrl: 'https://example.com/policies/social-media-draft-v1.0.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 1456789,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2024-11-15T14:20:00Z',
        changeNotes: 'Initial draft for review',
      },
    ],
    effectiveDate: '2025-01-01',
    createdBy: 'USR001',
    createdByName: 'John Admin',
    createdAt: '2024-11-15T14:20:00Z',
    viewCount: 45,
    mandatory: false,
  },
  {
    id: 'POL008',
    name: 'Anti-Harassment & Discrimination Policy',
    description: 'Zero-tolerance policy on harassment, discrimination, and creating a respectful workplace.',
    category: 'compliance',
    status: 'published',
    currentVersion: '2.3',
    versions: [
      {
        versionNumber: '2.3',
        documentId: 'DOC008-v23',
        documentUrl: 'https://example.com/policies/anti-harassment-v2.3.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 2345678,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2024-07-10T11:15:00Z',
        changeNotes: 'Enhanced reporting procedures and support resources',
      },
      {
        versionNumber: '2.2',
        documentId: 'DOC008-v22',
        documentUrl: 'https://example.com/policies/anti-harassment-v2.2.pdf',
        sourceType: 'upload',
        fileType: 'pdf',
        fileSize: 2245678,
        uploadedBy: 'USR001',
        uploadedByName: 'John Admin',
        uploadedAt: '2023-12-15T09:30:00Z',
        changeNotes: 'Updated definitions and examples',
      },
    ],
    effectiveDate: '2024-01-01',
    createdBy: 'USR001',
    createdByName: 'John Admin',
    createdAt: '2023-12-15T09:30:00Z',
    updatedAt: '2024-07-10T11:15:00Z',
    viewCount: 412,
    mandatory: true,
  },
];
